Module6 task2
htmlacademy-ecmascript/1157011-big-trip-12 pull request #11
Opened 2020-09-04 02:32 UTC by Serhiog

2020-09-04 08:42 UTC, ekazakov requested changes

2020-09-04 08:42 UTC, ekazakov commented on src/mock/point.js
> +        "src": generatePhotos(),
В src надо хранить одну ссылку на фото, а не массив. Обрати внимание что pictures д б массивом объектов содержащих ссылку на фото и текст с описанием

2020-09-04 08:42 UTC, ekazakov commented on src/mock/point.js
> -    price: getRandomInteger(25, 150),
Похоже случайно удалили поле price из мока

2020-09-04 08:42 UTC, ekazakov commented on src/presenter/group.js
> +      this._pointPresenter[point.id].init(point, this._innerTripPointList);
В init не надо передавать _innerTripPointList. Ты его уже передал в конструктор

2020-09-04 08:42 UTC, ekazakov commented on src/view/pointEditor.js
> +    this.setEditClickHandler(this._callback.editClick);
Вроде это обработчик задается в поинт презентере и тут уже не нужен

2020-09-04 08:42 UTC, ekazakov commented on src/view/pointEditor.js
> +    this._data = Object.assign({}, point);
Тут тоже надо использовать parseTaskToData

2020-09-04 08:42 UTC, ekazakov commented on src/view/pointEditor.js
> +    return Object.assign({}, point, { isFavorite: point.isFavorite !== null });
Кусок с isFavorite не нужен

2020-09-04 16:11 UTC, ekazakov requested changes

2020-09-05 07:57 UTC, Serhiog commented on src/mock/point.js
> +        "src": generatePhotos(),
> В src надо хранить одну ссылку на фото, а не массив. Обрати внимание что pictures д б массивом объектов содержащих ссылку на фото и текст с описанием

Поправил

2020-09-05 07:58 UTC, Serhiog commented on src/mock/point.js
> -    price: getRandomInteger(25, 150),
> Похоже случайно удалили поле price из мока

На самом деле, удалял специально т.к. все цены брал из offer.price. 
Вернул на место

2020-09-05 07:59 UTC, Serhiog commented on src/presenter/group.js
> +      this._pointPresenter[point.id].init(point, this._innerTripPointList);
> В init не надо передавать _innerTripPointList. Ты его уже передал в конструктор

Лишнее убрал

2020-09-05 08:01 UTC, Serhiog commented on src/view/pointEditor.js
> +    this.setEditClickHandler(this._callback.editClick);
> Вроде это обработчик задается в поинт презентере и тут уже не нужен

Убрал

2020-09-05 08:05 UTC, Serhiog commented on src/view/pointEditor.js
> +    this._data = Object.assign({}, point);
> Тут тоже надо использовать parseTaskToData

Сделал

2020-09-05 08:06 UTC, Serhiog commented on src/view/pointEditor.js
> +    return Object.assign({}, point, { isFavorite: point.isFavorite !== null });
> Кусок с isFavorite не нужен

Убрал

2020-09-05 08:08 UTC, Serhiog commented on src/presenter/trip.js
> +        this._points.price.sort((a, b) => b.price - a.price);
> `this._points.price.sort;` — `.price` все ломает, д.б просто `this._points.sort((a, b) => b.price - a.price);`

Сейчас сортировка используется как написал ты но сортирует не верно

2020-09-05 18:12 UTC, closed without merging