Module7 task1
htmlacademy-ecmascript/1157011-big-trip-12 pull request #12
Opened 2020-09-04 16:15 UTC by Serhiog

2020-09-05 16:28 UTC, ekazakov requested changes

2020-09-05 16:28 UTC, ekazakov commented on src/presenter/trip.js
> +        this._taskPresenter[data.id].init(data);
Тут будет `this._groupPresenter` и понадобится `dayNumber`

2020-09-05 16:28 UTC, ekazakov commented on src/presenter/trip.js
> +    }
Кажется в твоем проекте это не нужно. В учебном проекте есть кнопка показать больше задач, а в нашем сразу показываются все точки

2020-09-05 16:28 UTC, ekazakov commented on src/view/pointEditor.js
> +    this._callback.deleteClick(PointEditView.parsePointToData(this._data));
Тут нужно сделать отдельную статическую ф-ю parseDataToPoint

2020-09-05 16:41 UTC, ekazakov requested changes

2020-09-05 16:41 UTC, ekazakov commented on src/view/tripPoint.js
> +            € <span class="event__price-value">${totalOfferPrice}</span>
Тут надо `point.price`

2020-09-05 16:41 UTC, ekazakov commented on src/view/tripPoint.js
> +    })
Для одной точки не надо считать totalOfferPrice

2020-09-05 16:46 UTC, ekazakov requested changes

2020-09-05 16:46 UTC, ekazakov commented on src/view/pointEditor.js
> +    this.setfavoriteClickHandler();
Забыл передать уже сохраненные колбеки. От этого и была ошибка в pointEditor при перерисовке. Надо так:
```
 this.setDeleteClickHandler(this._callback.deleteClick);
 this.setEditClickHandler(this._callback.editClick);
 this.setfavoriteClickHandler(this._callback.favoriteClick);
```

2020-09-05 18:13 UTC, closed without merging

2020-09-06 01:14 UTC, Serhiog commented on src/presenter/trip.js
> +    }
> Этот код лучше перенести в `_renderGroup`
В group не нашел массива с точками чтобы к нему привязаться. Разве что делать пуш приходящих одиночных точек в новый массив и после этого смотреть его длину. Поэтому немного доработав вынес код выше в init презентора trip.

2020-09-06 01:20 UTC, Serhiog commented on src/presenter/trip.js
> +        this._taskPresenter[data.id].init(data);
> Тут будет `this._groupPresenter` и понадобится `dayNumber`

В смысле вместо  this._taskPresenter нужен this._groupPresenter ? dayNumber сверху передать сюда ?

2020-09-06 01:22 UTC, Serhiog commented on src/view/pointEditor.js
> +    this.setfavoriteClickHandler();
> Забыл передать уже сохраненные колбеки. От этого и была ошибка в pointEditor при перерисовке. Надо так:
> 
> ```
>  this.setDeleteClickHandler(this._callback.deleteClick);
>  this.setEditClickHandler(this._callback.editClick);
>  this.setfavoriteClickHandler(this._callback.favoriteClick);
> ```

Выходит, что именно для этого мы сохраняли колбеки ? Чтобы при сохранении обработчиков передать в них их cb ?

2020-09-06 03:26 UTC, Serhiog commented on src/view/tripPoint.js
> +    })
> Для одной точки не надо считать totalOfferPrice

Убрал

2020-09-06 03:26 UTC, Serhiog commented on src/view/tripPoint.js
> +            € <span class="event__price-value">${totalOfferPrice}</span>
> Тут надо `point.price`

Поменял

2020-09-06 03:39 UTC, Serhiog commented on src/view/pointEditor.js
> +    this._callback.deleteClick(PointEditView.parsePointToData(this._data));
> Тут нужно сделать отдельную статическую ф-ю parseDataToPoint

Создал такую функцию но не очень понимаю чем она должна отличаться от  parsePointoData, поэтому они получились одинаковые

2020-09-06 03:43 UTC, Serhiog commented on src/presenter/trip.js
> +    }
> Кажется в твоем проекте это не нужно. В учебном проекте есть кнопка показать больше задач, а в нашем сразу показываются все точки
Убрал