Module5 task1
htmlacademy-ecmascript/1157011-big-trip-12 pull request #6
Opened 2020-08-18 05:05 UTC by Serhiog

2020-08-19 08:17 UTC, ekazakov requested changes

2020-08-19 08:17 UTC, ekazakov commented on src/view/majorTripCost.js
> +    }
Не нужно, `points.forEach` не выкинет ошибку, т.к. колбэк в `forEach` не будет вызван для пустого массива. `totalPrice` останется 0.

2020-08-19 08:17 UTC, ekazakov commented on src/presenter/trip.js
> +    this._sortView = new TripSortView().getElement();
Надо просто `this._sortView = new TripSortView()`, `this._sortView` должно содержать ссылку на объект класса вьюхи

2020-08-19 08:17 UTC, ekazakov commented on src/presenter/trip.js
> +        pointComponent.removePointClickHandler(debounce(replacePointToEdit));
А зачем тут `debounce`? В задание это не требовалось

2020-08-19 08:17 UTC, ekazakov commented on src/view/pointEditor.js
> +    this._callback.editClick = callback;
Сюда не надо передавать `callback` и `this._callback.editClick = callback;` тоже лишнее

2020-08-19 08:17 UTC, ekazakov commented on src/view/tripPoint.js
> +    this._callback.editClick = callback;
Тоже callback не нужен

2020-08-19 21:18 UTC, Serhiog commented on src/view/majorTripCost.js
> +    }
> Не нужно, `points.forEach` не выкинет ошибку, т.к. колбэк в `forEach` не будет вызван для пустого массива. `totalPrice` останется 0.

Я так сделал для того чтобы соответствовать примеру разметке в котором при отсутствии точек не отображается total price

2020-08-19 21:20 UTC, Serhiog commented on src/view/majorTripCost.js
> +    }
> Не нужно, `points.forEach` не выкинет ошибку, т.к. колбэк в `forEach` не будет вызван для пустого массива. `totalPrice` останется 0.

По причине открытой dev tools справа, не заметил что total price отображается при отсутствии точек.

2020-08-19 21:26 UTC, Serhiog commented on src/presenter/trip.js
> +    this._sortView = new TripSortView().getElement();
> Надо просто `this._sortView = new TripSortView()`, `this._sortView` должно содержать ссылку на объект класса вьюхи

Если оставить this._sortView = new TripSortView() то как тогда будет рендериться сам элемент ? Ведь для функции render вторым параметром нужна разметка элемента

2020-08-19 21:27 UTC, Serhiog commented on src/presenter/trip.js
> +        pointComponent.removePointClickHandler(debounce(replacePointToEdit));
> А зачем тут `debounce`? В задание это не требовалось

Заметил баги если часто нажимать по кнопке открытия/закрытия.

2020-08-19 21:30 UTC, Serhiog commented on src/view/pointEditor.js
> +    this._callback.editClick = callback;
> Сюда не надо передавать `callback` и `this._callback.editClick = callback;` тоже лишнее

Разобрался. Исправил.

2020-08-19 21:32 UTC, Serhiog commented on src/view/tripPoint.js
> +    this._callback.editClick = callback;
> Тоже callback не нужен

Исправил.

2020-08-20 06:44 UTC, ekazakov commented on src/presenter/trip.js
> +    this._sortView = new TripSortView().getElement();
Мы уже рефакторили `render` и теперь он умеет сам доставать ссылку на DOM-элемент из вьюх

2020-08-20 06:46 UTC, ekazakov commented on src/presenter/trip.js
> +        pointComponent.removePointClickHandler(debounce(replacePointToEdit));
Надо будет разобраться с багом. debounce создает заметную задержку на переход в режим редактирования, да и в принципе не нужен

2020-08-20 11:35 UTC, ekazakov requested changes

2020-08-20 11:35 UTC, ekazakov commented on src/main.js
> +let originalPoints = [].slice.call(points);
можно просто `let originalPoints = points.slice();`

2020-08-20 11:35 UTC, ekazakov commented on src/presenter/trip.js
> +      });
Можно проще — ``` this._containerView.getElement().innerHTML = `` ```

2020-08-20 11:35 UTC, ekazakov commented on src/presenter/trip.js
>      const tripDaysContainer = document.querySelector(`.trip-days`);
Надо элемент получать через `this._containerView.getElement()`

2020-08-20 11:35 UTC, ekazakov commented on src/view/tripSort.js
> +  getSortBtn(callback) {
Лучше назвать `setSortButton`, т.к. тут мы устанавливаем некоторое значение

2020-08-20 11:35 UTC, ekazakov commented on src/presenter/trip.js
> +    document.querySelector(`#sort-price`).addEventListener(`click`, setSort)
Обработчик события надо навешивать через методы `TripSortView`

2020-08-23 16:47 UTC, Serhiog commented on src/main.js
> +let originalPoints = [].slice.call(points);
> можно просто `let originalPoints = points.slice();`

Упростил

2020-08-23 16:49 UTC, Serhiog commented on src/presenter/trip.js
> +      });
> Можно проще — `` this._containerView.getElement().innerHTML = `` ``

Не нашел этого в коде. Видимо уже убрал

2020-08-23 17:11 UTC, Serhiog commented on src/presenter/trip.js
>      const tripDaysContainer = document.querySelector(`.trip-days`);
> this._containerView.getElement()

исправил

2020-08-23 17:12 UTC, Serhiog commented on src/view/tripSort.js
> +  getSortBtn(callback) {
> Лучше назвать `setSortButton`, т.к. тут мы устанавливаем некоторое значение

исправлено

2020-08-23 17:14 UTC, Serhiog commented on src/presenter/trip.js
> +    document.querySelector(`#sort-price`).addEventListener(`click`, setSort)
> Обработчик события надо навешивать через методы `TripSortView`

Было исправлено ранее

2020-08-27 20:04 UTC, merged