Module6 task1 2
htmlacademy-ecmascript/1157011-big-trip-12 pull request #7
Opened 2020-08-23 18:17 UTC by Serhiog

2020-08-23 21:53 UTC, ekazakov requested changes

2020-08-23 21:53 UTC, ekazakov commented on src/presenter/header.js
> +    this._siteHeaderFilterTrip = this._siteHeaderMainTripContainer.querySelector(`.trip-main__trip-controls`);
Тут надо использовать View-класс и еще надо вынести в компонент код из index.html

```
<div class="trip-main__trip-controls  trip-controls">
          <h2 class="visually-hidden">Switch trip view</h2>
          <h2 class="visually-hidden">Filter events</h2>
        </div>
        <button class="trip-main__event-add-btn  btn  btn--big  btn--yellow" type="button">New event</button>
```

2020-08-23 21:53 UTC, ekazakov commented on src/presenter/trip.js
> +        this._points.sort((a, b) => b.price - a.price);
Ф-ю выполняющее сравнение надо вынести в отдельный файл. См. учебный проект https://github.com/htmlacademy-ecmascript/taskmanager-12/blob/master/src/utils/task.js#L54

2020-08-23 21:53 UTC, ekazakov commented on src/presenter/trip.js
> +  _sortingPoints() {
Посмотри как разделена сортировка задач и их отрисовка в учебном проекте (https://github.com/htmlacademy-ecmascript/taskmanager-12/blob/master/src/presenter/board.js#L63). Подумай как сделать такое же с точками

2020-08-23 21:53 UTC, ekazakov commented on src/presenter/trip.js
> +          this.renderPoint(tripPointListElement4Price.querySelector(`.trip-events__list`), point);
Чтобы избавиться от `querySelector` надо будет разбить `TripPointListView` на несколько частей. Обсудим на консультации

2020-08-23 21:53 UTC, ekazakov commented on src/presenter/trip.js
> +  }
Нашел 2 бага:
1. Точку можно переключить в режим редактирования и обратно только один раз. Дальше кнопка «разворачивания» точки не реагирует.
2. Если развернуть, а затем свернуть точку и нажать клавишу `ESC` появится ошибка в консоле.
Попробуй с дебаггером и найти в чем причина

2020-08-23 21:53 UTC, ekazakov commented on src/main.js
> +const TripBoardPresenter = new BoardPointsPresenter(siteSiteMainContainer, points);
Не совсем понял зачем нужен `TripBoardPresenter`

2020-08-25 19:02 UTC, Serhiog commented on src/consts.js
> +};
> Не совсем верно выразился на консультации `SORT_TYPES` — это не константа, а перечисление. Смотри как их оформляют в учебном проекте https://github.com/htmlacademy-ecmascript/taskmanager-12/blob/master/src/const.js

Переделал

2020-08-25 19:11 UTC, Serhiog commented on src/main.js
> +render(siteSiteMainContainer, new NoPoints(points), RenderPosition.AFTEREND);
> `NoPoints` д.б. частью `TripPresenter` и рендериться в нем

Перенес

2020-08-25 20:00 UTC, Serhiog commented on src/presenter/header.js
> +    this._siteHeaderFilterTrip = this._siteHeaderMainTripContainer.querySelector(`.trip-main__trip-controls`);
> Тут надо использовать View-класс и еще надо вынести в компонент код из index.html
> 
> ```
> <div class="trip-main__trip-controls  trip-controls">
>           <h2 class="visually-hidden">Switch trip view</h2>
>           <h2 class="visually-hidden">Filter events</h2>
>         </div>
>         <button class="trip-main__event-add-btn  btn  btn--big  btn--yellow" type="button">New event</button>
> ```

От query selector тут избавился. Разметку кнопки вынес в отдельный файл.

2020-08-25 20:18 UTC, Serhiog commented on src/presenter/trip.js
> +        this._points.sort((a, b) => b.price - a.price);
> Ф-ю выполняющее сравнение надо вынести в отдельный файл. См. учебный проект https://github.com/htmlacademy-ecmascript/taskmanager-12/blob/master/src/utils/task.js#L54

Не совсем понял что нужно сделать

2020-08-25 20:19 UTC, Serhiog commented on src/presenter/trip.js
> +  _sortingPoints() {
> Посмотри как разделена сортировка задач и их отрисовка в учебном проекте (https://github.com/htmlacademy-ecmascript/taskmanager-12/blob/master/src/presenter/board.js#L63). Подумай как сделать такое же с точками

Тоже пока не придумал как. Но попробую разбить на отдельные части существующие методы.

2020-08-25 21:50 UTC, Serhiog commented on src/presenter/trip.js
> +          this.renderPoint(tripPointListElement4Price.querySelector(`.trip-events__list`), point);
> Чтобы избавиться от `querySelector` надо будет разбить `TripPointListView` на несколько частей. Обсудим на консультации

Избавился.

2020-08-25 21:51 UTC, Serhiog commented on src/main.js
> +const TripBoardPresenter = new BoardPointsPresenter(siteSiteMainContainer, points);
> Не совсем понял зачем нужен `TripBoardPresenter`

Убрал.

2020-08-25 21:54 UTC, Serhiog commented on src/presenter/trip.js
> +  }
> Нашел 2 бага:
> 
> 1. Точку можно переключить в режим редактирования и обратно только один раз. Дальше кнопка «разворачивания» точки не реагирует.
> 2. Если развернуть, а затем свернуть точку и нажать клавишу `ESC` появится ошибка в консоле.
>    Попробуй с дебаггером и найти в чем причина

Починил.

2020-08-26 08:09 UTC, ekazakov requested changes

2020-09-03 10:28 UTC, Serhiog commented on src/view/innerPointsList.js
> +  }
> Конструктор тут можно совсем удалить

Удалил

2020-09-05 18:12 UTC, closed without merging